server: 
   port: 9090
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/siteapp
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: temp
      file-size-threshold: 5MB
      max-file-size: 1MB
      max-request-size: 5MB
        
jwt:
  header: Authorization
  secret: tasksSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
      info: info
      
file:      
  storage:
    location: fileStorage
         